/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;
import java.util.HashMap;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}

